name: Deploy Backend to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_API_SERVICE: ${{ secrets.RENDER_API_SERVICE }}
        run: |
          curl -X POST "https://dashboard.render.com/web/srv-cvdniqbv2p9s7393f2ig?key=${{ secrets.RENDER_API_KEY }}"
